config/routes.rb
RckApp::Application.routes.draw do
  get "pages/index"
  get "pages/road"
  get "pages/dirt"
  get "pages/hobby"
  get "pages/competition"
  get "pages/partys"
  get "pages/about"
  get "pages/schedule"
  root :to => "pages#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def road
  end

  def dirt
  end

  def hobby
  end

  def competition
  end

  def partys
  end

  def about
  end
  
  def schedule
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.email, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
          <div class="container">
  <div class="navbar-header">
      
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <a class="navbar-brand" href="#"><%=image_tag "logo.png" %></a>
  </div>
     
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>    <%=link_to 'Home', root_url%></li>
    
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>  <%=link_to 'Racing',  pages_road_path%></li>
           <li>  <%=link_to 'Pro Shop', pages_hobby_path%></li>
             <li>  <%=link_to 'Competition', pages_competition_path%></li>
                <li>  <%=link_to 'Partys', pages_partys_path%></li>
          
        
        </ul>


           <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Company<b class="caret"></b></a>
        <ul class="dropdown-menu">
              <li><a href="#" data-toggle="modal" data-target="#myModal3">Hours</a></li>
             <li>  <%=link_to 'About Us', pages_about_path%></li>
              <li>  <%=link_to 'Photos', root_url%></li>
           <li>  <%=link_to 'Videos', root_url%></li>
        
          
         
       
        </ul>
              <li>  <%=link_to 'Schedule', pages_schedule_path%></li>
       
            <li><a href="#" data-toggle="modal" data-target="#myModal2">Rates</a></li>
              <li><a href="#" data-toggle="modal" data-target="#myModal">Contact</a></li>
         
  

    </ul>
   
   
  </div>
  </div>               

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rck App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rck App" %>">
      <link href='http://fonts.googleapis.com/css?family=Raleway:400,500,600,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  

    <%= csrf_meta_tags %>
      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <div class="trim"></div>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
      <div class="footer">
     <div class="container">
         
         
         
         
           <div class="col-md-3">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h4 class="titlesServices">Navigation</h4>
     
      <ul class="list-unstyled">
        <li> <%=link_to 'Home', root_url%></li>
        
          
              <li><a href="#" data-toggle="modal" data-target="#myModal2">Rates</a></li>
          
         
       
        <li><%=link_to 'Schedule',pages_schedule_path%></li>
            <li><a href="#">SiteMap</a></li>
      
            <li><a href="#" data-toggle="modal" data-target="#myModal">Contact</a></li>
</ul>
 
      
     
      
      
         </div>
       </div>
               
               
               
               
               
        
                       
      </div>
         
         
         
         
         
         
         
         
         
         
         
         
         
         <div class="col-md-3">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h4 class="titlesServices">Services</h4>
     
      <ul class="list-unstyled">
            <li><%=link_to 'Racing', pages_road_path%></li>         
               <li><%=link_to 'Pro Shop', pages_hobby_path%></li>  
                <li><%=link_to 'Competitions', pages_competition_path%></li>  
                <li><%=link_to 'Partys', pages_partys_path%></li>   
        
          
         
        
         
          
</ul>
 
      
     
      
      
         </div>
       </div>
               
               
               
               
               
        
                       
      </div>
         
         
         
         
            <div class="col-md-3">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h4 class="titlesServices">Company</h4>
     
      <ul class="list-unstyled">
               <li>  <%=link_to 'About Us', pages_about_path%></li>
           <li><a href="#" data-toggle="modal" data-target="#myModal3">Hours</a></li>
            <li><a href="#">Videos</a></li>
            <li><a href="#">Photos</a></li>
           
</ul>
 
      
     
      
      
         </div>
       </div>
               
               
               
               
               
        
                       
      </div>
         
         
         
         
            <div class="col-md-3">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h4 class="titlesServices">Location</h4>
     
      <address>
  <strong>RC Kinetics</strong><br>
  2739 6th Ave<br>
  Troy NY, 12180<br>
  <abbr title="Phone">P:</abbr> (518) 456-7890
</address>
 
      
     
      
      
         </div>
       </div>
               
               
               
               
               
        
                       
      </div>
         
         
         
         
         
         
         
         
         
        
        
        </div>
        
       
      <!--hero last end-->
    
    </div>
    <footer>
       <div class="container">
           
           <div class="col-md-6">
              <h6>&copy;copyright 2014 RC Kinetics</h6>
           </div>
           
           
              <div class="col-md-6">
                  <div class="pull-right">
                <a href="https://www.facebook.com/rckinetics">    <%=image_tag "facebook_icon.png"%></a> 
                        <a href="https://www.facebook.com/rckinetics">    <%=image_tag "twitter_icon.png"%></a> 
                        <a href="https://www.facebook.com/rckinetics">    <%=image_tag "google_icon.png"%></a> 
                        <a href="https://www.facebook.com/rckinetics">    <%=image_tag "youtube_icon.png"%></a> 
                  
                      </div>
           
           </div>
        
     
              
           
    
        
        </div>
    
    </footer>
    
    
    
    
      <!-- contact model -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Contact Us</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" role="form">
             <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input type="name" class="form-control" id="inputName" placeholder="Name">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="textMessage" class="col-sm-2 control-label">Inquiry</label>
    <div class="col-sm-10">
   <textarea class="form-control" rows="3"  placeholder="Inquiry"></textarea>
    </div>
  </div>
 
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
        
        
        
        
        
        
        
        
            <!-- rates model -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Rates</h4>
      </div>
      <div class="modal-body">
       <table class="table">
          <tr>
          <th>Services</th>
               <th>Price</th>
        </tr>
           
           
             <tr>
          
          <td>Practice</td>
                 <td>10.00</td>
              
          
          </tr>
          
          <tr>
          
          <td>Racing Competitions</td>
                 <td>20.00</td>
              
          
          </tr>
          
          
             <tr>
          
          <td>Partys</td>
                 <td>100.00</td>
              
          
          </tr>
          
         
          
          
          </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
        
        
        
        
        
           
          <!-- hours model -->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">RCK Hours</h4>
      </div>
      <div class="modal-body">
      <table class="table">
          <tr>
          <th>Days</th>
               <th>Hours</th>
        </tr>
          
          <tr>
          
          <td>Monday</td>
                 <td>Closed</td>
              
          
          </tr>
          
          
             <tr>
          
          <td>Tuesday</td>
                 <td>Closed</td>
              
          
          </tr>
          
          <tr>
          
          <td>Wednesday</td>
                 <td>11am to 11pm</td>
              
          
          </tr>
          
          
          
             <tr>
          
          <td>Thursday</td>
                 <td>11am to 11pm</td>
              
          
          </tr>
          
          
             <tr>
          
          <td>Friday</td>
                 <td>11am to 11pm</td>
              
          
          </tr>
          
          
             <tr>
          
          <td>Saturday</td>
                 <td>11am to 11pm</td>
              
          
          </tr>
          
          
          
             <tr>
          
          <td>Sunday</td>
                 <td>11am to 6pm</td>
              
          
          </tr>
          
          
          </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
  </body>
</html>

app/views/pages/about.html.erb
<div class="about_page">
  
  <div class="about_mast">
  
    <div class="container">
         <div class="headline">
      <h1 id="responsive_headline"><%=image_tag 'rpm.png'%>Inside RC Kinetics</h1>
      </div>
    
     </div>
  
  
     </div>
  
 
              
  <div class="container">
                 
              <div class="row">
      <div class="col-md-12 about-us">
  
    <h2>About RCK</h2>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          'Mauris ac tellus ac justo feugiat hendrerit a a leo. Donec et quam eleifend, molestie nunc ut, adipiscing ligula.
          Phasellus sed scelerisque est. Donec volutpat arcu metus, tempus lacinia libero volutpat non. Curabitur pulvinar pellentesque cursus.
          Aliquam vel tortor ante. Quisque quis ipsum rhoncus, aliquam lacus sed, vehicula arcu. Suspendisse et lacus fermentum, tristique elit interdum, vehicula odio.
          Proin fringilla elit semper, auctor magna sed, pulvinar libero. Donec interdum orci orci, sit amet tincidunt risus fermentum vitae. Vivamus nec velit felis.   </p>
        
        
         <h2>Our Goals</h2>
           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          'Mauris ac tellus ac justo feugiat hendrerit a a leo. Donec et quam eleifend, molestie nunc ut, adipiscing ligula.
          Phasellus sed scelerisque est. Donec volutpat arcu metus, tempus lacinia libero volutpat non. Curabitur pulvinar pellentesque cursus.
          Aliquam vel tortor ante. Quisque quis ipsum rhoncus, aliquam lacus sed, vehicula arcu. Suspendisse et lacus fermentum, tristique elit interdum, vehicula odio.
          Proin fringilla elit semper, auctor magna sed, pulvinar libero. Donec interdum orci orci, sit amet tincidunt risus fermentum vitae. Vivamus nec velit felis.   </p>
        
        
        
          <h2>What we offer</h2>
           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          'Mauris ac tellus ac justo feugiat hendrerit a a leo. Donec et quam eleifend, molestie nunc ut, adipiscing ligula.
          Phasellus sed scelerisque est. Donec volutpat arcu metus, tempus lacinia libero volutpat non. Curabitur pulvinar pellentesque cursus.
          Aliquam vel tortor ante. Quisque quis ipsum rhoncus, aliquam lacus sed, vehicula arcu. Suspendisse et lacus fermentum, tristique elit interdum, vehicula odio.
          Proin fringilla elit semper, auctor magna sed, pulvinar libero. Donec interdum orci orci, sit amet tincidunt risus fermentum vitae. Vivamus nec velit felis.   </p>
        
    </div>
    
   
                
    </div>
  
  
  </div>
  
  
  
  
  
  
  
  
  
</div>

app/views/pages/competition.html.erb
 <div class="party">
       <div class="container">
       
         <div class="mini-hero text-center">
         
           <h1 id="responsive_headline">Competitions</h1>
                    
           </div>
       
          </div>


         </div>
     <div class="container">
    <div class="services-page">
      
    
    
   
             
        
        <div class="row">
            
            
            
                   <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices">TBA</h3> 
      
      
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
        
      
      
         </div>
       </div>
                       
      </div>
            
           
        
        
        
        
         <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices">TBA</h3>
     
      
     
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
         
      
      
      
         </div>
       </div>
                       
      </div>
            
            
        
        
        
         <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices">TBA</h3>
     
      
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
       
      
      
         </div>
       </div>
                       
      </div>
            
             </div>
        
        </div>
            
            </div>
        
        
        
        
        
        
        
       <div class="comp-page">
          <div class="hero4">
    
    
    
    
    </div>
       
    </div>
    
    
    
    
     <div class="comp-page">
          <div class="details">
    
    
    
    
    </div>
       
    </div>

app/views/pages/dirt.html.erb
<h1>Pages#dirt</h1>
<p>Find me in app/views/pages/dirt.html.erb</p>

app/views/pages/hobby.html.erb
   <div class="hobby-shop">  
    <div class="party">
       <div class="container">
       
         <div class="mini-hero text-center">
         
         <h1 id="responsive_headline">  <%=image_tag 'gears.png'%>Pro Shop</h1>
                    
           </div>
       
          </div>


         </div>
     

     <div class="container">
    <div class="services-page">
      
    
    
   
             
        
        <div class="row">
            
            
            
                   <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices"><%=image_tag 'tire_icons.png'%><span>Sales</span></h3> 
      
      
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
        
      
      
         </div>
       </div>
                       
      </div>
            
           
        
        
        
        
         <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices"><%=image_tag 'shock_icon.png'%><span>Parts</span></h3>
     
      
     
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
         
      
      
      
         </div>
       </div>
                       
      </div>
            
            
        
        
        
         <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices"><%=image_tag 'repairs_icons.png'%><span>Repairs</span></h3>
     
      
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
       
      
      
         </div>
       </div>
                       
      </div>
            
             </div>
        
        </div>
            
            </div>
        
        
        
        
        
        
        
       <div class="services-page">
          <div class="hero4">
    
    
    
    
    </div>
       
    </div>
    
    
    
    
     <div class="services-page">
          <div class="details">
    
    
    
    
    </div>
       
    </div>
     
     
     </div>

app/views/pages/index.html.erb
   <!--Jumbo-->
  <div class="container-fluid">
<div class="jumbotron">
    
 
   
    <div class="container">
    
       
      
                  
          <div class="headline">
            <h1 id="responsive_headline">Rc racing is here,get into it</h1>
            
            <h4 id="responsive">RC Kinectics New Yorks Premire RC Racing Facilty </h4>
      </div>
               
         
        
      
        
        
           
          
        
      
        
    
         
    
     </div><!--end container-->
    
    
    
    
    </div><!--end jumbo-->
      </div>
    
    
    
       <div class="heroSub"></div>
    
    
    
    
    
    
        <div class="container">
         <div class="services">
          <div class="row">
            
               <h2 class="titles">Services
                     <div class="lines"></div>
              </h2>
               
           
                   <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices">Racing</h3>
     
      
      <h4>TageLine Header</h4>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
          <h5>TageLine Header</h5>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
          <a href="#">Learn More<%=image_tag "arrow_icon_16.png"%></a> 
      
      
         </div>
       </div>
                       
      </div>
              
              
              
              
              
                <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices">Hobby Shop</h3>
     
      
      <h4>TageLine Header</h4>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
          <h5>TageLine Header</h5>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
          <a href="#">Learn More<%=image_tag "arrow_icon_16.png"%> </a>
      
      
         </div>
       </div>
                       
      </div>
              
              
              
              
              
              
              
              
                <div class="col-md-4">
          
           <div class="panel panel-default">
  <div class="panel-body">
    <h3 class="titlesServices">Events</h3>
     
      
      <h4>TageLine Header</h4>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
      
          <h5>TageLine Header</h5>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
      
      
          <a href="#">Learn More <%=image_tag "arrow_icon_16.png"%></a>
      
      
         </div>
       </div>
                       
      </div>
                  
                  
                  
                  
                   </div><!--end row-->                 
                   
               </div>
             
               
         
        
      
        
        

        
        
    
     </div><!--end container-->
        
    
    
    
    
    
      <!--start hobby-->
    <div class="hero3">
    
    
    
    
    </div>
      <div class="hero4">
    
    
    
    
    </div>
          

    
      <!--end hobby-->
    
    
    
        <!--staff-->
    
    
    
    
    
    
     
        
        <div class="container">
                 <div class="staff">
                     <div class="row">
       <h2 class="titles">RCK Staff
            
               <div class="lines"></div>
            
            </h2>
            
             <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
       <%=image_tag "31.png"%>
     
      <div class="caption">
        <h3 class="text-center">Alex Kiekel</h3>
        <p>Hi my name is Alex, I have been in the hobby since age 10! I competed across the nation and won multiple awards. Multiple TCS ( Tamiya Championship Series) top 3 finishes, including 1st place winner of the Formula 1 Classes. I am the owner of R/C Kinetics, if you need any pointers, help or just have any questions do not hesitate to ask. See you in the races! </p>
        <p>   <a href="#"  class="learn">Learn More <%=image_tag "arrow_icon_16.png"%> </a></p>
      </div>
    </div>
  </div>
            
            
            
            
             <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
         <%=image_tag "peeps.png"%>
      <div class="caption">
        <h3  class="text-center">Danny Varjo</h3>
          <p>My names Danny, I work doing the digital and print work for facility. I also take care of some maintenance in the shop. Im new to the RC world, but eager to join in on the fun. </p>
        <p>   <a href="#"  class="learn">Learn More <%=image_tag "arrow_icon_16.png"%></a></p>
      </div>
    </div>
  </div>
            
            
            
            
             <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
         <%=image_tag "12.png"%>
      <div class="caption">
        <h3  class="text-center">Ben Rck</h3>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante enim, accumsan sagittis lobortis mattis, ornare sit amet orci. Nulla elit orci, dignissim vitae ornare eget, iaculis</p>
        <p>   <a href="#" class="learn">Learn More <%=image_tag "arrow_icon_16.png"%></a></p>
      </div>
    </div>
  </div>
        </div>
        </div>
     </div>
    
  
 
       <!--staff end-->
    
    
    
    
      <!--hero last-->
    <div class="hero_last">
        <div class="action_hero">
    <h2 class="text-center">Ready for Speed? <span><a href=#>Contact us.</a></span></h2>
    </div>
    </div>
      <!--hero last end-->
    
    
    
    
    
    
     <!--hero last-->

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>